version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres-iot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
